# Generated by Django 4.0.5 on 2022-10-15 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='follows',
        ),
        migrations.AddField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(blank=True, to='twitter.tweet'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='bio',
            field=models.TextField(blank=True, default="hey I'm using Twitter", max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='location',
            field=models.CharField(blank=True, default='no location of user registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
