# Generated by Django 4.0.5 on 2022-06-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='bio',
            field=models.TextField(blank=True, default="hey I'm using Twitter", max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='location',
            field=models.CharField(blank=True, default='no location of user registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
