# Generated by Django 4.0.5 on 2022-11-05 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='twitter_user_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
