# Generated by Django 4.0.5 on 2022-06-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_alter_twitteruser_bio_alter_twitteruser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(null=True, to='twitter.tweet'),
        ),
    ]
