# Generated by Django 4.0.5 on 2022-07-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_alter_twitteruser_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='follows',
        ),
    ]
